### ISSUE TITLE
How to test coreth locally

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/coreth#192]
Hi, since  avalanchego invokes coreth binary directly, so, when run avalanchego and set breakpoints in coreth it's useless. It won't stop.

May I know how you guys debug coreth?

**Comment by aaronbuchwald** [comment]
It really depends on what you're testing, but since AvalancheGo now imports coreth instead of running it as a binary you should be able to insert breakpoints.

Personally, I prefer debugging unit tests to the running binary as it's usually possible to narrow issues down to one section of the code and then debug a unit test of the specific behavior.
