### ISSUE TITLE
Blocks not being produced for transactions

### ISSUE THREAD

**Issue by AaronKutch** [ava-labs/coreth#197]
I have a repro here https://github.com/AaronKutch/avalanchego_block_bug . Run `bash run.sh`. What this does is start `avalanchego` with a genesis file that prefunds a 0xBf... account, and I want to make a transaction to send some of the funds fo a 0xb3 account. The log file has as its last line
```
INFO [06-29|03:59:07.594] <C Chain> github.com/ava-labs/coreth/internal/ethapi/api.go:1745: Submitted transaction hash=0xc0ea83c5c1b2ba2b2d1ae9d3748b87625044acd4f562ae79bf02f49f77e0a763 from=0xBf660843528035a5A4921534E156a27e64B231fE nonce=0 recipient=0xb3d82b1367D362DE99aB59A658165AFf520CBd4d value=10,000,000,000,000,000,000,000,000 type=0 gasFeeCap=30,000,000,000 gasTipCap=30,000,000,000 gasPrice=30,000,000,000
```
I expect that a block should be produced almost immediately to include the transaction, but the chain just sits there. After 20 seconds we check the account funds and block number and see that nothing has changed. Strangely, I do get blocks if contracts are submitted.

**Comment by aaronbuchwald** [comment]
In the genesis file here: https://github.com/AaronKutch/avalanchego_block_bug/blob/master/ETHGenesis.json, it looks like you are specifying that there should be 5 validators in the initial staking set, but from what I can tell the script is only starting one node.

If you specify your own genesis, you need to make sure to run nodes with the nodeIDs of the initial staking set in the genesis. If for example only 20% of the network is online, then the network won't have liveness and may not be able to make progress.

I'd recommend running with the local network ie. `--netework-id=local` instead to make life easier. For testing purposes, the local network comes with a private key that is included in the code so that you can use a prefunded key in local testing: https://github.com/ava-labs/avalanchego/blob/master/genesis/genesis_local.go#L18.

Could you provide the details of exactly what you're trying to accomplish with this script and maybe we can add that as a feature request to the avalanche-network-runner here: https://github.com/ava-labs/avalanche-network-runner.

**Comment by aaronbuchwald** [comment]
Assuming that this has been resolved based on the above answer. If not, please feel free to re-open the issue.
