### ISSUE TITLE
Returned error: missing trie node 2f8085f8623e60106aa0fb711b495f6de52d59cc8b527b881fa773a478888a22

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/coreth#312]
(migrated from AvalancheGo: https://github.com/ava-labs/avalanchego/issues/1932)

Hi, it was recommended in the Discord to open up this issue.

I've been running an Avalanche-Go archive node for almost a year and started receiving the below errors when attempting to make C-chain JSONRPC calls for an AVAX balances. I'm not sure if my chaindata became corrupt over time (4.7 TB total), perhaps is there a way to revert my C-chain to <x> block to restart archive node syncing from that particular point?

`Returned error: missing trie node 2f8085f8623e60106aa0fb711b495f6de52d59cc8b527b881fa773a478888a22`

I was on the Cortina.8 release when the errors appeared, upgraded to Cortina.9 and still seeing the same issues.

I'm running my node with the below flags:

`docker run -d -it --ulimit nofile=1000000:1000000 --restart unless-stopped --stop-timeout 300 --log-opt max-size=10m --name avax-mainnet -v /avalanchego/mainnet:/root -p 127.0.0.1:9650:9650 -p 9651:9651 avaplatform/avalanchego:b820b46e /avalanchego/build/avalanchego --index-enabled=true --http-host=0.0.0.0 --http-port=9650 --staking-port=9651 --api-ipcs-enabled=true --chain-config-dir=/root/.avalanchego/configs/chains --http-allowed-origins=* --http-allowed-hosts=*`

My `./configs/chains/C/config.json` has the `debug` flag in the `eth-apis` section with `"pruning-enabled": false`, and has been successfully making archive & state balance requests since last year until recently.

**Comment by ymonye** [comment]
Thanks,

I have no idea regarding `state-sync`, but yes I have been running an archive node since September 2022 and indexing historical txns, states, AVAX balances, & token balances, while being able to successfully place JSONRPC requests for historical states until recently.

I was on the Cortina.8 release when the errors occurred; at one point I had to reboot my server, restarted the AVAX docker image (built from Cortina.8) and saw that error when attempting to get AVAX balances for that particular block (34406857). After pulling the source for Cortina.9 from Github, building both the source `./scripts/build.sh` & the docker image `./scripts/build_image.sh`, I encountered the same problem.

I will see if I can populate missing txns from that block. So do I just add the below to my `./C/config.json` file?:

`"populate-missing-tries": 34406857`

Assuming block 34406857 is where the `missing trie node` error originated?

**Comment by ymonye** [comment]
> Thanks,
> 
> I have no idea regarding `state-sync`, but yes I have been running an archive node since September 2022 and indexing historical txns, states, AVAX balances, & token balances, while being able to successfully place JSONRPC requests for historical states until recently.
> 
> I was on the Cortina.8 release when the errors occurred; at one point I had to reboot my server, restarted the AVAX docker image (built from Cortina.8) and saw that error when attempting to get AVAX balances for that particular block (34406857). After pulling the source for Cortina.9 from Github, building both the source `./scripts/build.sh` & the docker image `./scripts/build_image.sh`, I encountered the same problem.
> 
> I will see if I can populate missing txns from that block. So do I just add the below to my `./C/config.json` file?:
> 
> `"populate-missing-tries": 34406857`
> 
> Assuming block 34406857 is where the `missing trie node` error originated?

Hi, bump @aaronbuchwald

**Comment by ymonye** [comment]
> Thanks,
> 
> I have no idea regarding `state-sync`, but yes I have been running an archive node since September 2022 and indexing historical txns, states, AVAX balances, & token balances, while being able to successfully place JSONRPC requests for historical states until recently.
> 
> I was on the Cortina.8 release when the errors occurred; at one point I had to reboot my server, restarted the AVAX docker image (built from Cortina.8) and saw that error when attempting to get AVAX balances for that particular block (34406857). After pulling the source for Cortina.9 from Github, building both the source `./scripts/build.sh` & the docker image `./scripts/build_image.sh`, I encountered the same problem.
> 
> I will see if I can populate missing txns from that block. So do I just add the below to my `./C/config.json` file?:
> 
> `"populate-missing-tries": 34406857`
> 
> Assuming block 34406857 is where the `missing trie node` error originated?

This seems to have resolved my issue, thanks team
