### ISSUE TITLE
Block.Hash produces a wrong hash

### ISSUE THREAD

**Issue by sosedoff** [ava-labs/coreth#46]
Running `block.Hash()` produces a wrong hash when comparing to the actual hash from the RPC response.
Filing the ticket per @aaronbuchwald request.

Code to reproduce the issue: 

```go
package main

import (
	"context"
	"log"

	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, err := ethclient.Dial("https://api.avax-test.network/ext/bc/C/rpc")
	if err != nil {
		log.Fatal(err)
	}

	header, err := client.HeaderByNumber(context.Background(), nil)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("block number:", header.Number)
	log.Println("block hash:", header.Hash().Hex())

        // This will fail as `header.Hash()` returns an invalid hash value
	header2, err := client.HeaderByHash(context.Background(), header.Hash())
	if err != nil {
		log.Fatal(err)
	}

	log.Println("fetched number:", header2.Number)
	log.Println("fetched hash:", header2.Hash().Hex())
}
```

**Comment by aaronbuchwald** [comment]
Closing this issue since it has been resolved by using ethclient. The issue was a result of changes to the Eth Block format to include an extra data field and a version field, to support atomic transactions. This resulted in the hash calculated by the node and the hash calculated by client libraries that ignored this field producing a different hash from the block.
