### ISSUE TITLE
Why is the consensus engine dummy? Is it not fully developed?

### ISSUE THREAD

**Issue by liyue201** [ava-labs/coreth#601]
Why is the consensus engine dummy? Is it not fully developed?

**Comment by ARR4N** [comment]
There's an extended explanation in the [README](https://github.com/ava-labs/coreth/tree/master/consensus/dummy) but, in summary, it's because the `consensus` directory is inherited from [ethereum/go-ethereum](https://github.com/ethereum/go-ethereum) while our consensus is performed by [ava-labs/avalanchego](https://github.com/ava-labs/avalanchego/). You can think of the `coreth` repo as only the execution layer.

If this answers your question can you please close the issue?
